apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application1
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/image-list: application1=europe-central2-docker.pkg.dev/distroless-329216/distroless/application1
    argocd-image-updater.argoproj.io/application1.update-strategy: digest
spec:
  destination:
    namespace: application1
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: chart
    repoURL: {{ .Values.spec.github.repository }}
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
      - ../application1.values.yaml
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true